# $FreeBSD$

PORTNAME=	simdjson
PORTVERSION=	0.3.1
DISTVERSIONPREFIX=	v
CATEGORIES=	devel

MAINTAINER=	olevole@olevole.ru
COMMENT=	Parsing gigabytes of JSON per second

LICENSE=	APACHE20

USES:=		cmake:insource

USE_GITHUB=	yes
GH_ACCOUNT=	simdjson
GH_PROJECT=	simdjson

.include <bsd.port.mk>
